Main
ellite/Wallos pull request #105
Opened 2024-02-08 17:37 UTC by lslschr

Adding input validation

2024-02-08 20:38 UTC, ellite requested changes
Thank you.
I left some comments.

2024-02-08 20:38 UTC, ellite commented on endpoints/categories/category.php
> +        $categoryName = validate("Category");
This value "Category" is hardcoded and not a user input, no need for validation here.

2024-02-08 20:38 UTC, ellite commented on endpoints/currency/currency.php
> +        $currencyName = validate("Currency");
Same on this three.

2024-02-08 20:38 UTC, ellite commented on endpoints/household/household.php
> +        $householdName = validate("Member");
Same here.

2024-02-08 21:16 UTC, lslschr commented
Hi 
Thank you very much for the feedback. 

Just removed the unnecessary validations.

2024-02-09 10:14 UTC, ellite approved these changes
Thank you.

2024-02-10 12:58 UTC, merged

2024-02-13 22:11 UTC, lslschr commented
Just wanted to mention the reason for this PR: 
The application wallos in the version 0.9 is vulnerable to Cross-Site Scripting (XSS) affecting all text-based input fields across the application, where input validation is not properly implemented. To exploit this vulnerability, the attacker can insert the following payload into a text-based input field: <script>alert("xss")</script>. Once saved, refreshing the browser will trigger the execution of this JavaScript code in the user's browser. Similarly, the script will execute when a different user accesses the application and encounters the injected payload.

So the vulnerability is a XSS vulnerability at all text-based input fields and the root cause for this vulnerability is the missing input validation or the incorrect implementation of these. This input validation was created as part of this PR and the vulnerability was therefore closed. 

The XSS vulnerability affects the security of users who use the application. Other users will experience the same vulnerability when using the application. XSS can cause a variety of problems for the end user that range in severity from an annoyance to complete account compromise. The most severe XSS attacks involve disclosure of the user’s session cookie, allowing an attacker to hijack the user’s session and take over the account.