feat(notifications): add multi email recipients
ellite/Wallos pull request #504
Opened 2024-08-23 14:04 UTC by teschiopol

If I need to translate all label, please let me know and I'll try my best. 

If something is not on your coding style, I'll fix it. 

Ty

2024-08-23 14:06 UTC, teschiopol commented
I mispell the branch, it's issue 436

2024-08-23 16:18 UTC, ellite commented
Thanks.
I've been sick and then quite busy trying to catch up at work. I'll try to look at everything that happened on GitHub this week. I've seen quite a few emails.
I'll review this as soon as possible.

2024-08-23 16:33 UTC, ellite commented on endpoints/cronjobs/sendcancellationnotifications.php
> +        $mail['otherEmail'] = $row["other_email"];
`$email `vs $mail

2024-08-23 16:33 UTC, ellite commented on endpoints/cronjobs/sendnotifications.php
> +        $mail['otherEmail'] = $row["other_email"];
`$email` vs $mail

2024-08-23 16:36 UTC, ellite requested changes
Thanks. 
Just saw two small mistakes, if you don't mind fixing them.
I will handle the remaining translations. Thanks.

2024-08-24 09:20 UTC, teschiopol commented
Done and sorry.

2024-08-24 09:22 UTC, ellite commented
Nothing to be sorry about.
Thank you very much.

When I have some time I will test and merge.

Regards.

2024-09-01 13:23 UTC, ellite approved these changes
Thank you.

2024-09-01 13:24 UTC, merged