update to be at the same level as en.js
ellite/Wallos pull request #99
Opened 2024-01-30 01:25 UTC by devzwf

this is to align with with the lastest change in en.js

2024-01-30 08:47 UTC, ellite requested changes
I believe there were some ' removed by mistake.

2024-01-30 08:47 UTC, ellite commented on scripts/i18n/fr.js
> +    error_deleting_subscription: "Erreur lors de la suppression de labonnement",
Should be l'abonnement

2024-01-30 08:47 UTC, ellite commented on scripts/i18n/fr.js
> +    failed_to_load_subscription: "Impossible de charger labonnement",
l'abonnement

2024-01-30 08:47 UTC, ellite commented on scripts/i18n/fr.js
> +    edit_subscription: "Modifier labonnement",
l'abonnement

2024-01-30 08:47 UTC, ellite commented on scripts/i18n/fr.js
> +    network_response_error: "La réponse du réseau nétait pas correcte",
n'était

2024-01-30 12:44 UTC, devzwf commented
let me review and get back

2024-01-30 13:00 UTC, devzwf reviewed
should be good now

2024-02-02 08:30 UTC, ellite approved these changes

2024-02-02 08:31 UTC, merged